load("//neoform:bundle_extract.bzl", "bundle_extract")
load("//neoform:decompile.bzl", "decompile_jar")
load("//neoform:inject.bzl", "inject_sources")
load("//neoform:merge.bzl", "merge_jars")
load("//neoform:merge_mappings.bzl", "merge_mappings")
load("//neoform:rename.bzl", "rename_jar")
load("//neoform:split.bzl", "split_jar")

exports_files(["rules_neoforge_tools_install.json"])

bundle_extract(
    name = "extract_server",
    src = "@minecraft_1_21_1//:downloads/server.jar",
)

split_jar(
    name = "split_client",
    src = "@minecraft_1_21_1//:downloads/client.jar",
    classes = "client_classes.jar",
    resources = "client_resources.jar",
)

split_jar(
    name = "split_server",
    src = ":extract_server",
    classes = "server_classes.jar",
    resources = "server_resources.jar",
)

merge_jars(
    name = "merge",
    client = ":client_classes.jar",
    server = ":server_classes.jar",
    version = "1.21.1",
)

merge_mappings(
    name = "merge_mappings",
    mappings = "@neoform//:config/joined.tsrg",
    official = "@minecraft_1_21_1//:downloads/client.txt",
)

rename_jar(
    name = "rename",
    src = ":merge",
    libraries = "@minecraft_1_21_1//:libraries",
    mappings = ":merge_mappings",
)

decompile_jar(
    name = "decompile",
    src = ":rename",
    libraries = "@minecraft_1_21_1//:libraries",
)

inject_sources(
    name = "inject",
    src = ":decompile",
    inject = "@neoform//:inject",
)
